In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('weatherAUS.csv')


In [3]:
dataset.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [4]:
x=dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
y=dataset.iloc[:,-1].values

In [5]:
x
y

array(['No', 'No', 'No', ..., 'No', 'No', nan], dtype=object)

In [6]:
x


array([['Albury', 13.4, 22.9, ..., 16.9, 21.8, 'No'],
       ['Albury', 7.4, 25.1, ..., 17.2, 24.3, 'No'],
       ['Albury', 12.9, 25.7, ..., 21.0, 23.2, 'No'],
       ...,
       ['Uluru', 5.4, 26.9, ..., 12.5, 26.1, 'No'],
       ['Uluru', 7.8, 27.0, ..., 15.1, 26.0, 'No'],
       ['Uluru', 14.9, nan, ..., 15.0, 20.9, 'No']], dtype=object)

In [7]:
y

array(['No', 'No', 'No', ..., 'No', 'No', nan], dtype=object)

In [8]:
y=y.reshape(-1,1)  #1d list to 2d list

 Dealing with invalid dataset

In [9]:
from sklearn.impute import SimpleImputer


In [10]:
imputer=SimpleImputer(missing_values=np.nan,strategy="most_frequent")

In [11]:
x=imputer.fit_transform(x)
y=imputer.fit_transform(y)

In [12]:
x

array([['Albury', 13.4, 22.9, ..., 16.9, 21.8, 'No'],
       ['Albury', 7.4, 25.1, ..., 17.2, 24.3, 'No'],
       ['Albury', 12.9, 25.7, ..., 21.0, 23.2, 'No'],
       ...,
       ['Uluru', 5.4, 26.9, ..., 12.5, 26.1, 'No'],
       ['Uluru', 7.8, 27.0, ..., 15.1, 26.0, 'No'],
       ['Uluru', 14.9, 20.0, ..., 15.0, 20.9, 'No']], dtype=object)

In [13]:
y

array([['No'],
       ['No'],
       ['No'],
       ...,
       ['No'],
       ['No'],
       ['No']], dtype=object)

#Encoding

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le1=LabelEncoder()
x[:,0]=le1.fit_transform(x[:,0])
le2=LabelEncoder()
x[:,4]=le2.fit_transform(x[:,4])
le3=LabelEncoder()
x[:,5]=le3.fit_transform(x[:,5])
le4=LabelEncoder()
x[:,7]=le4.fit_transform(x[:,7])
le7=LabelEncoder()
x[:,6]=le7.fit_transform(x[:,6])
le6=LabelEncoder()
x[:,-1]=le6.fit_transform(x[:,-1])
le5=LabelEncoder()
y=le5.fit_transform(y)

C:\Users\onepi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [16]:
x

array([[2, 13.4, 22.9, ..., 16.9, 21.8, 0],
       [2, 7.4, 25.1, ..., 17.2, 24.3, 0],
       [2, 12.9, 25.7, ..., 21.0, 23.2, 0],
       ...,
       [41, 5.4, 26.9, ..., 12.5, 26.1, 0],
       [41, 7.8, 27.0, ..., 15.1, 26.0, 0],
       [41, 14.9, 20.0, ..., 15.0, 20.9, 0]], dtype=object)

#Feature Scaling(To keep data in a certain range(-3,3 in our case) to plot graph in a definite range)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc=StandardScaler()


In [19]:
x=sc.fit_transform(x)

In [20]:
x

array([[-1.53166617,  0.19132753, -0.04135977, ..., -0.01407077,
         0.02310362, -0.52979545],
       [-1.53166617, -0.75105231,  0.26874452, ...,  0.03244663,
         0.387799  , -0.52979545],
       [-1.53166617,  0.11279588,  0.35331842, ...,  0.62166712,
         0.22733303, -0.52979545],
       ...,
       [ 1.20928479, -1.06517892,  0.52246622, ..., -0.69632607,
         0.65037966, -0.52979545],
       [ 1.20928479, -0.68822699,  0.53656187, ..., -0.29317521,
         0.63579185, -0.52979545],
       [ 1.20928479,  0.42692249, -0.45013361, ..., -0.30868102,
        -0.10818671, -0.52979545]])

#Splitting Dataset into training and testing dataset

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [23]:
x_train

array([[ 0.22535368,  1.03946939,  0.07140543, ...,  0.68369032,
         0.08145488, -0.52979545],
       [ 1.42012717, -0.45263203,  0.11369237, ..., -0.41722163,
         0.22733303, -0.52979545],
       [ 0.50647685, -0.20133073, -0.14002932, ..., -0.06058818,
        -0.02065982,  1.88752093],
       ...,
       [ 1.0687232 ,  0.75675544,  0.93124006, ...,  1.10234698,
         1.07342629, -0.52979545],
       [ 0.57675765, -0.04426743, -0.16822062, ...,  0.01694083,
        -0.28324049,  1.88752093],
       [ 1.63096955, -0.0285611 , -0.91529006, ..., -0.35519842,
        -0.76463838, -0.52979545]])

In [24]:
x_test

array([[-1.46138537,  1.52636564,  2.28442243, ...,  1.98617771,
         2.00704644,  1.88752093],
       [ 1.27956559,  1.30647701,  2.01660509, ...,  1.59853265,
         2.05080989, -0.52979545],
       [ 0.85788082, -1.11229791, -0.84481181, ..., -1.06846532,
        -0.80840182, -0.52979545],
       ...,
       [ 0.71731924, -0.24844973, -1.0985335 , ..., -0.97543051,
        -1.12933375,  1.88752093],
       [ 0.57675765,  1.00805673,  0.52246622, ...,  0.66818452,
         0.60661622, -0.52979545],
       [ 0.92816162, -0.81387763, -0.90119441, ..., -0.71183187,
        -0.73546275, -0.52979545]])

In [25]:
y_train

array([1, 0, 0, ..., 0, 0, 0])

In [26]:
y_test

array([1, 1, 0, ..., 1, 0, 0])

#Training model, Using Random Forset Classifier

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
cs=RandomForestClassifier(n_estimators=100,random_state=0)

In [29]:
cs.fit(x_train,y_train)

RandomForestClassifier(random_state=0)

In [30]:
cs.score(x_train,y_train)

0.9999312525780283

In [37]:
y_pred=cs.predict(x_test)

In [38]:
y_pred=le6.inverse_transform(y_pred)


In [39]:
 y_pred

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [40]:
y_test=le6.inverse_transform(y_test)

In [41]:
y_test

array(['Yes', 'Yes', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [42]:
y_test=y_test.reshape(-1,1)
y_pred=y_pred.reshape(-1,1)

In [50]:
df=np.concatenate((y_test,y_pred),axis=1)
dataframe=pd.DataFrame(df,columns=['Rain Tomorrow','Prediction'])

In [51]:
dataframe

Rain Tomorrow Prediction
0               Yes         No
1               Yes         No
2                No         No
3                No        Yes
4                No         No
...             ...        ...
29087            No        Yes
29088            No         No
29089           Yes         No
29090            No         No
29091            No         No

[29092 rows x 2 columns]

In [52]:
from sklearn.metrics import accuracy_score


In [53]:
accuracy_score(y_test,y_pred)

0.8521930427608965